### PR TITLE
Bugfix: TINF-234 - "Forgot Password" looks extremely out of place. (+ Enhancements to the google sign in graphic)

### PR DESCRIPTION
**Pull request by lepathie**
# really cheap
Hacked something together that works on the outside but makes me cry on the inside.
The existing css file would need some serious refurbishment.

## Fixes
https://pw-netz.atlassian.net/browse/TINF-234

### Solution
image

## Enhancements that are out of scope and could need some further polish:
**Google-SignIn graphic still needs some customization but I don't have the software for it. See: https://developers.google.com/identity/branding-guidelines**
Maybe @cgomm could add a "Google" to the graphic and update coloring to fit HappyHamster.

**Also** *, hardcoded literals in css should be replaced with text symbol or another solution.*
For now, as our keycloak is english only, I don't think it's that disastrous.

### CODE REVIEW

**Comment by lepathie** [comment]
Waiting for @cgomm to send me the updated graphics the next days. Will be ready then.

**Comment by lepathie** [comment]
Replaced the existing google-signin graphic with something that fits the directive of google.

**Comment by lepathie** [comment]
Also removed the hard-coded text in front of the 3rd party logins.

**Review by DavidSchmidt00 — APPROVED** [review]

**Comment by DavidSchmidt00** [comment]
Ist nicht geil, aber wird eh neu gemacht ^^

**Review by floriangoelz — APPROVED** [review]

**Pull request merged**
